### ISSUE TITLE
MLU220 编译ffmpeg之后，没有对应的编解码器

### ISSUE THREAD

**Issue by iwanlebron** [Cambricon/ffmpeg-mlu#33]
MLU220-EVB 编译ffmpeg之后，没有对应的编解码器 #33

**Comment by ivanlebron** [comment]
Linux localhost.localdomain 3.10.0-1160.49.1.el7.x86_64 #1 SMP Tue Nov 30 15:51:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

系统为x86-64 不需要交叉编译，下面这个报错 怎么解决

[root@localhost ffmpeg-mlu]# source compile_ffmpeg.sh MLU200
ffmpeg-mlu directory not exit, now download ...
Cloning into 'ffmpeg'...
remote: Enumerating objects: 7060, done.
remote: Counting objects: 100% (7060/7060), done.
remote: Compressing objects: 100% (6058/6058), done.
remote: Total 7060 (delta 1868), reused 2767 (delta 739), pack-reused 0
Receiving objects: 100% (7060/7060), 14.84 MiB | 6.59 MiB/s, done.
Resolving deltas: 100% (1868/1868), done.
mkdir: created directory ‘/root/ffmpeg-mlu/ffmpeg-mlu/build’
gcc is unable to create an executable file.
If gcc is a cross-compiler, use the --enable-cross-compile option.
Only do this if you know what cross compiling means.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
make: *** No targets specified and no makefile found.  Stop.
******** compile and preparations are ready ******** 
******** the compiled files are in the ffmpeg-mlu folder ********

**Comment by ivanlebron** [comment]
忽略上面的问题 为什么编译好之后 不存在对应的编解码器
加速硬件是有的
<img width="1187" alt="image" src="https://github.com/Cambricon/ffmpeg-mlu/assets/105045937/1dc04493-eb30-47c1-9bd3-49a9cb3b5727">
编解码没有 
<img width="1320" alt="image" src="https://github.com/Cambricon/ffmpeg-mlu/assets/105045937/89992a38-669d-45f5-ae53-00e6a61da071">

**Comment by hairuiGo** [comment]
你好，尝试下 如下命令： `./ffmpeg -decoders | grep mlu`
请在运行之前设置环境变量，如：LD_LIBRARY_PATH等
