### ISSUE TITLE
如何编译使用？文档在哪里？

### ISSUE THREAD

**Issue by yand9807** [Cambricon/ffmpeg-mlu#44]
请问如何进行建议使用，readme中剃刀的文档在哪里？《Cambricon-FFmpeg-MLU-User-Guide-CN-v3.x.x.pdf》

**Comment by hairuiGo** [comment]
请联系和您对接的相关工作人员处获取；

**Comment by yand9807** [comment]
这个是不公开的吗？我是用的是云服务器，没有寒武纪官方工作人员的联系方式，通过service@cambricon.com邮箱询问也没有得到回复

**Comment by yand9807** [comment]
已经联系到了，谢谢

**Comment by hairuiGo** [comment]
感谢您的提问；由于内部正在做文档的统一更新，故最近几个版本均未带文档，如需，请从如下渠道获取。

推荐如下方式：
1.从对接的相关工作人员出获取；
2.开发者论坛，sdk页面：https://forum.cambricon.com/list-47-1.html; 这里有专门的销服同事负责；
3.公司市场侧对外邮箱：service@cambricon.com
4.github 仓库issues版块提问；

为了效率高，可以都尝试，感谢您的提问；

**Comment by hairuiGo** [comment]
如有问题，随时联系，感谢
