### ISSUE TITLE
MLU220 Edge

### ISSUE THREAD

**Issue by Kevin4ch** [Cambricon/ffmpeg-mlu#8]
修改编译脚本如下：
../configure \
  --prefix="${FFMPEG_LIB_DIR}" \
  --extra-libs="-lpthread -lm" \
  --extra-cflags=-I/usr/local/neuware/include \
  --extra-ldflags=-L/usr/local/neuware/lib64 \
  --extra-libs="-lcnrt -lcncodec -lcndrv -ldl" \
  --enable-ffplay \
  --enable-ffmpeg  --enable-mlumpp --enable-gpl --enable-version3 --enable-nonfree --disable-static --enable-stripping --enable-optimizations --enable-cross-compile --enable-shared --arch=aarch64  --cross-prefix=/opt/Atlas2.0SDK/dir_for_docker_dev/cross_compile/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-  --target-os=linux

结果是

gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc is unable to create an executable file.
C compiler test failed.

编译器路径有效

**Comment by Hairuijy** [comment]
you could  make the following operation:

./configure \   
--enable-cross-compile \   
--target-os=linux \  
--arch=arm64 \    
--cross-prefix="<PATH>/edge/gcc-linaro-6.5.0-2018.12-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-" \    
--cc=aarch64-linux-gnu-gcc \   
 --enable-version3 \    
--enable-gpl \   
 --disable-debug \    
--enable-pthreads \    
--disable-yasm \    
--disable-asm \    
--disable-static \    
--enable-shared \    
--prefix="./enable_lib" \    
--disable-stripping \   
 --disable-optimizations \    
--enable-mlumpp \    
--extra-cflags="-I<PATH>i/edge/neuware/pc/include" \   
 --extra-ldflags="-L<PATH>/edge/neuware/pc/lib64" \    
--extra-cflags=-fPIC \   
 --extra-libs="-lcncodec -lcnrt -ldl -lcndev -lcndrv -lion -ljpu" 

make -j && make install

**Comment by Hairuijy** [comment]
Check whether the results are correct, you could run cmd:
`file ffmpeg
`
result:
￼`
ffmpeg: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=e141490ea4cc7cf323fdce12894a7b3368b7e8af, with debug_info, not stripped

`
